### PR TITLE
fixed multiple 'interface' values in .toc files

### PR DESCRIPTION
**Pull request by torkus**

### CODE REVIEW

**Comment by Meorawr** [comment]
The game client supports multiple interface versions in upcoming patches, so this isn't needed.

**Comment by Ghostopheles** [comment]
As Meo mentioned, the game supports comma-delimited interface versions - I appreciate the effort but this change isn't necessary.

**Comment by torkus** [comment]
@Meorawr , besides [the wiki](https://wowpedia.fandom.com/wiki/TOC_format), does a proper specification exist for .toc file content with RFCs etc?

**Comment by Meorawr** [comment]
That's the old wiki and per the wonderful banner at the top of the article, that page isn't being updated anymore. Refer to [the new wiki instead](<https://warcraft.wiki.gg/wiki/TOC_format>) which has this change documented in the "Interface version" section of the page.

And no - there's no formal specification for TOC files.

**Comment by torkus** [comment]
I took a look at the references on the wiki and ... are you guys getting all your information by scouring decompiled WoW code? Doesn't Blizzard give you more of a branch than that? (I'm not an addon developer).

**Comment by Ghostopheles** [comment]
Blizzard addons have TOCs that follow the format, so we look through those and figure out what each field does. Most of them are fairly self-explanatory. Occasionally (very rarely) the community will get a heads-up for incoming changes, but generally it's simple enough to just read the existing TOCs and figure it out from there.

Also, referencing the comma-delimited interface versions - this is something that was recently added in patch 10.2.7 
 for mainline and patch 4.4.0 for Cata Classic, so relatively it's a relatively new feature that isn't supported yet on 10.2.6, though the first interface number doesn't throw an error and still works as expected.

**Comment by torkus** [comment]
Thanks guys for your insight and for the link, this is very helpful.

_edit_: fyi @layday, I'm sure you know about this already, but just in case.

**Comment by layday** [comment]
Thanks, I released a version supporting multiple interface versions earlier today.

**Comment by layday** [comment]
Also, to add, this means that `release.json` might have multiple entries for the same flavour going forward, in case you need to adjust anything in strongbox.

**Pull request closed without merging**
